---
- name: JBoss eap migration
  become: true
  gather_facts: false
  strategy: free
  vars:
    current_eap_home: "/opt/jboss-eap-7.1"
    eap_home: "/opt/jboss-eap-{{ eap }}"
    eap_service: "jboss-eap"
    erase_eap_tmp: "yes"
    erase_os_tmp: "no"
    target: "dc"
    jdk_version: "{{ jdk }}"
    stop_time: "{{ stop }}"
    start_time: "{{ start }}"

  hosts: "{{ target }}"

  tasks:
    - name: Set owership of EAP home folder
      file:
        path: "{{ eap_home }}"
        owner: jboss
        group: jboss
        recurse: yes

    - name: update jboss eap service daemon
      lineinfile:
        path: /etc/default/jboss-eap.conf
        regexp: 'JBOSS_HOME='
        line: JBOSS_HOME={{ eap_home }}

    - name: configure eap with jdk 11
      lineinfile:
        path: /etc/default/jboss-eap.conf
        regexp: 'JAVA_HOME='
        line: '#JAVA_HOME=/usr/java/default'
      when: jdk_version == "11"

    - name: configure eap with jdk 8
      lineinfile:
        path: /etc/default/jboss-eap.conf
        regexp: 'JAVA_HOME='
        line: 'JAVA_HOME=/usr/java/default'
      when: jdk_version == "8"

    - name: Stop JBoss EAP
      service:
        name: "{{ eap_service }}"
        state: stopped

    - name: Stopping JBoss EAP
      pause:
        seconds: "{{ stop_time }}"

    - name: Clear OS Cache /tmp
      shell: "rm -rf /tmp/*"
      when: erase_os_tmp == "yes"

    - name: Clear JBoss EAP Cache
      shell: "rm -rf {{ eap_home }}/domain/tmp"
      when: erase_eap_tmp == "yes"

    - name: Clear JBoss EAP servers Cache
      shell: "rm -rf {{ eap_home }}/domain/servers/*/tmp"
      when: erase_eap_tmp == "yes"

    - name: Start JBoss EAP
      service:
        name: "{{ eap_service }}"
        state: started

    - name: Starting JBoss EAP
      pause:
        seconds: "{{ start_time }}"
