---
- name: JBoss undeploy wars 
  hosts: dc
  become: true
  gather_facts: true
  vars:
    eap_home: "/opt/jboss-eap-7.2/"
    sg: "A"
  tasks:
    - name: list server groups
      shell: ./jboss-cli.sh -c --controller={{ ansible_facts['default_ipv4']['address'] }}:9990 --command="ls server-group" | tr " " "\n" | sed "/^$/d" | grep {{ sg }}
      args:
        chdir: "{{ eap_home }}/bin"
      register: server_group_list 

    - debug:
        msg: "{{ server_group_list.stdout_lines }}"

    - set_fact:
        server_groups: "{{ server_group_list.stdout_lines }}"

    - name: copy batch file
      template:
        src: template/undeploy.py.j2
        dest: /tmp/batch.py
        owner: jboss
        group: jboss

    - name: run script
      shell: "python /tmp/batch.py"
