---
- name: JBoss deploy wars
  hosts: dc
  become: true
  serial: 1
  gather_facts: true
  vars:
    eap_home: "/opt/jboss-eap-7.2/"
    jdk: "8"
  tasks:
    - name: Copy wars to the domain controller
      unarchive:
        src: files/wars-{{ jdk }}.tar
        dest: /tmp/
        owner: jboss
        group: jboss

    - name: Copy batch file
      template:
        src: template/upload_wars.cli.j2
        dest: /tmp/batch.cli
        owner: jboss
        group: jboss

    - name: Upload all wars to the jboss eap repo
      shell: "./jboss-cli.sh -c --controller={{ ansible_facts['default_ipv4']['address']}}:9990 --file=/tmp/batch.cli"
      args:
        chdir: "{{ eap_home }}/bin"

    - name: clean up
      file:
        path: /tmp/batch.cli
        state: absent
