---
- name: JBoss deploy wars
  hosts: dc
  become: true
  vars:
    eap_home: "/opt/jboss-eap-7.2/"
    sg: "A"
    jdk: "8"
  tasks:
    - name: copy batch file
      template:
        src: template/deploy-{{ jdk }}.cli.j2
        dest: /tmp/batch.cli
        owner: jboss
        group: jboss

    - name: deploy all war from group {{ sg }}
      shell: "./jboss-cli.sh -c --controller={{ ansible_facts['default_ipv4']['address'] }}:9990 --file=/tmp/batch.cli"
      args:
        chdir: "{{ eap_home }}/bin"
      ignore_errors: true

    - name: clean up
      file:
        path: /tmp/batch.cli
        state: absent
